footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 3.0
publish_frequency: 2.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.0
raytrace_range: 5.5

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser_scan_sensor point_cloud_sensor
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

    point_cloud_sensor: {sensor_frame: laser_link, clearing: true, topic: cloud, data_type: PointCloud, marking: true}

inflation:
    inflation_radius: 0.55
